config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/signin' => 'signin#index'
  post '/login' => 'signin#login'
  post '/logout' => 'session#logout'

  resources :comments
  resources :posts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments

  validates :email, length: { minimum: 5 }
  # validates :password, length: { minimum: 6 }

  def full_name
    "#{fname} #{lname}".strip
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user

  private

  def current_user
    begin
      @current_user = session[:user_id] && User.find(session[:user_id])
    rescue
      puts "session[:user_id] error (#{session[:user_id]})"
      session[:user_id] = nil
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  def self.recent( num = 10 )
    self.order( id: :desc ).limit( num )
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = @current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.post, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    post = @comment.post
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  def self.recent( num = 10 )
    self.order( id: :desc ).limit( num )
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = @current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    user = @post.user
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def logout
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.password == params[:password]
      session[:user_id] = @user.id
      flash[:notice] = "Hi #{@user.fname}!"
      redirect_to '/'
    else
      flash[:notice] = "We were unable to authenticate you"
      redirect_to '/signin'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def self.recent( num = 10 )
    self.order( id: :desc ).limit( num )
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if User.find_by(email: params[:user][:email])
        format.html { redirect_to '/users/new', notice: 'An account with that email already exists.' }
      elsif @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        session[:user_id] = @user.id
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.transaction do
      @user.posts.each{ |post| post.comments.destroy_all }
      @user.posts.destroy_all
      @user.comments.destroy_all
      @user.destroy
    end
    respond_to do |format|
      format.html { redirect_to '/', notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :bio, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="commentform">
    <%= form.text_area :body, id: :comment_body, placeholder: 'Comment' %> <br>
    <%= form.hidden_field :post_id, id: :comment_post_id %>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<% if @current_user && @current_user.id == @comment.user.id %>
  <h1>Editing Comment</h1>

  <%= render 'form', comment: @comment %>
<% else %>
    <a href='/comments/<%= @comment.id %>'>This is not your comment!</a>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user.full_name %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post.title %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %>

app/views/home/index.html.erb
<% if @current_user %>
    <%= render 'posts/form', post: Post.new %>
<% else %>
  <a href="/signin">
    <div class="homepage">
      <div class="hometext">please sign in</div>
    </div>
  </a>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>It's Time...</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <div class="topbox">
        <span class="sessionlink"><%= flash[:notice] %> <%= link_to 'Logout', '/logout', method: :post %></span>
      </div>
    <% else %>
      <div class="topbox">
        <span class="sessionlink"><%= flash[:notice] %> <a href='/signin'>Sign In</a></span>
      </div>
    <% end %>
    <nav>
      <ul>
        <li><a href="/">Home</a></li>
      <%if @current_user %>
        <li><a href="/users/<%= @current_user.id %>">Profile</a></li>
      <% else %>
        <li><a href="/signin">Profile</a></li>
      <% end %>
        <li><a href="/posts">Feed</a></li>
        <li><a href="/users">Explore</a></li>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="newpostbox">
    <h1>Make a post!</h1>
    <%= form.text_field :title, id: :post_title, placeholder: 'Title' %><br>
    <%= form.text_area :body, id: :post_body, placeholder: 'Body' %><br>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% if @current_user && @current_user.id == @post.user.id %>
  <h1>Editing Post</h1>

  <%= render 'form', post: @post %>
<% else %>
  <a href='/posts/<%= @post.id %>'>This is not your post!</a>
<% end %>

app/views/posts/index.html.erb
<div class="profileposts">
  <h2>New Posts</h2>
    <% @posts.order( id: :desc ).each do |post| %>
      <a href='/posts/<%= post.id %>'>
        <div class="profilepost">
        <strong><%= post.title %></strong><br>
        <%= post.body %><br>
        Post by: <%= post.user.full_name %>
        </div>
      </a>
    <% end %>
  </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="profileposts">
  <div class="profilepost">
    <h3><%= @post.title %></h3>
    <p id="timestamps">Post created at: <%= @post.created_at.strftime("%H:%M") %> <%= @post.created_at.strftime("%d %b. %Y") %></p>
    <p><%= @post.body %></p>
  <% if @current_user && @current_user.id == @post.user_id %>
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% else %>
  Posted by: <a href="/users/<%= @post.user_id %>"><%= @post.user.full_name %></a>
  <% end %>
  </div>
  <% if @current_user %>
    <%= render 'comments/form', comment: Comment.new(post_id: @post.id) %>
  <% end %>
  <% @post.comments.order( id: :desc ).each do |comment| %>
    <div class="commentbody">
      <p><%= comment.body %></p>
      <p id="timestamps">Comment created at: <%= comment.created_at.strftime("%H:%M") %> <%= comment.created_at.strftime("%d %b. %Y") %></p>
      <% if @current_user && @current_user.id == comment.user_id %>
        <em>Your comment:</em> <a href="/comments/<%= comment.id %>/edit">Edit</a> | <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% elsif @current_user && @current_user.id == @post.user_id %>
        <a href='/users/<%= comment.user_id %>'><%= comment.user.full_name %></a><br>
        <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% else %>
        <a href='/users/<%= comment.user_id %>'><%= comment.user.full_name %></a>
      <% end %>
    </div>
  <% end %>
</div>

app/views/signin/index.html.erb
<% if @current_user %>
		<h1>Welcome, <%= @current_user.full_name %></h1>
<% else %>
  <div class="signinform">
    <h1>Sign In</h1>
  	<%= form_tag '/login' do %>
  	<%= text_field_tag :email, nil, placeholder: 'email' %> <br>
  	<%= password_field_tag :password, nil, placeholder: 'password' %> <br>
  	<%= submit_tag 'Login' %> <br><br><br>
    <a href="/users/new">I don't have an account.</a>
  	<% end %>
  </div>
	<img class="cheetah" src="http://orig03.deviantart.net/4c91/f/2012/234/3/3/cheetah_runcycle_by_lui_ysia-d5c1833.gif">
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="signinform">
    <h1>Sign Up</h1>
    <%= form.text_field :fname, id: :user_fname, placeholder: 'first name' %><br>
    <%= form.text_field :lname, id: :user_lname, placeholder: 'last name' %><br>
    <%= form.text_field :bio, id: :user_bio, placeholder: 'bio' %><br>
    <%= form.text_field :email, id: :user_email, placeholder: 'email' %><br>
    <%= form.password_field :password, id: :user_password, placeholder: 'password' %><br>
    <%= form.submit %><br><br><br>
    <a href="/signin">I already have an account.</a>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if @current_user && @current_user.id == @user.id %>
  <h1>Editing User</h1>

  <%= render 'form', user: @user %>
<% else %>
  <a href='/users/<%= @user.id %>'>This is not your account!</a>
<% end %>

app/views/users/index.html.erb
<div class="profileposts">
  <h2>New Users</h2>
    <% @users.order( id: :desc ).each do |user| %>
    <a href='/users/<%= user.id %>'>
      <div class="profilepost">
        <strong><%= user.full_name %><br></strong>
        <%= user.bio %><br>
      </div>
    </a>
    <% end %>
</div>

app/views/users/new.html.erb
<%= render 'form', user: @user %>
<img class="cheetah" src="http://orig03.deviantart.net/4c91/f/2012/234/3/3/cheetah_runcycle_by_lui_ysia-d5c1833.gif">

app/views/users/show.html.erb
<div class="about">
  <p>
    <strong>Name:</strong>
    <%= @user.full_name %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= @user.bio %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <% if @current_user && @current_user.id == @user.id %>
    <br>
    <%= link_to 'Edit Profile', edit_user_path(@user) %> | <%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% else %>
  <% end %>
</div>
<div class="profileposts">
<h2>Posts:</h2>
  <% @user.posts.order( id: :desc ).each do |post| %>
    <a href='/posts/<%= post.id %>'>
      <div class="profilepost">
      <strong><%= post.title %></strong><br>
      <%= post.body %>
      </div>
    </a>
  <% end %>
</div>